Add getting-started to part 2
ISSOtm/gb-asm-tutorial pull request #21
Opened 2022-07-11 21:27 UTC by eievui5

2022-07-11 21:55 UTC, avivace requested changes
Looks already very nice! Thanks @eievui5 !

2022-07-11 21:55 UTC, avivace commented on src/part2/getting-started.md
> +The next few lines wait until "VBlank". This basically means that the Game Boy's PPU has went to sleep for a short time, during which we can do things like turning off the screen.
`has went to sleep` doesn't sound right here

2022-07-11 21:55 UTC, avivace commented on src/part2/getting-started.md
> +Turning off the screen is important because it puts the PPU to sleep until the screen is turned back on. You can only load new graphics while the PPU is sleeping, so this gives us time to load our ti
This is a bit confusing. Previously we say that during "VBlank the PPU goes to sleep", but then we affirm that we need to turn the screen off during VBlank to put the PPU to sleep. Maybe we could clarify?

2022-07-11 21:55 UTC, avivace commented on src/part2/getting-started.md
> +This loop might look familiar if you've read part 1. It copies `Tiles` to `$9000`, which is a part of VRAM where tiles are stored. To get the length of `Tiles`, we use another label at the end, calle
It's `a part` or `the part` of the VRAM where tiles are stored?

2022-07-11 21:55 UTC, avivace commented on src/part2/getting-started.md
> +In the "Hello, world!" lesson, you saw graphics which were wirtten out by hand in hexadecimal. This time, we're going to write our graphics in a more friendly way; by assigning a character to each sh
```suggestion
In the "Hello, world!" lesson, you saw graphics which were written out by hand in hexadecimal. This time, we're going to write our graphics in a more friendly way; by assigning a character to each shade! To do this, type `dw`, followed by a space, a backtick (\`) and a series of 8 characters; by default these are 0, 1, 2, and 3, from lightest to darkest. This defines a row of 8 pixels.
```

2022-07-11 21:59 UTC, Rangi42 commented on src/part2/getting-started.md
> +In this lesson we will start a new project from scratch, an arkanoid clone called "Unbricked"! (Or any other name you like, as this is *your* project)
[Breakout](https://en.wikipedia.org/wiki/Breakout_%28video_game%29) ([Arkanoid](https://en.wikipedia.org/wiki/Arkanoid)) (I personally recognize the name "Breakout" more, and it was first)
```suggestion
In this lesson we will start a new project from scratch, a [Breakout](https://en.wikipedia.org/wiki/Breakout_%28video_game%29) ([Arkanoid](https://en.wikipedia.org/wiki/Arkanoid)) clone called "Unbricked"! (Or any other name you like, as this is *your* project)
```

2022-07-11 22:00 UTC, Rangi42 commented on src/part2/getting-started.md
> +Open a terminal and make new directory, like you did for "Hello, world!" (`mkdir unbricked`), and then enter it (`cd unbricked`).
```suggestion
Open a terminal and make a new directory (`mkdir unbricked`), and then enter it (`cd unbricked`), just like you did for "Hello, world!".
```

2022-07-11 22:01 UTC, Rangi42 commented on src/part2/getting-started.md
> +Start by creating a file called `main.asm`, and include hardware.inc in your code.
Should all filenames be monospace?
```suggestion
Start by creating a file called `main.asm`, and include `hardware.inc` in your code.
```

2022-07-11 22:05 UTC, Rangi42 commented on src/part2/getting-started.md
> +The next few lines wait until "VBlank". This basically means that the Game Boy's PPU has went to sleep for a short time, during which we can do things like turning off the screen.
If you haven't already, would it be a good idea to start with a high-level explanation of what VBlank and HBlank even are? Just summarizing the idea of a beam going top to bottom, left to right, with some overscan in both directions during which the screen isn't being drawn on and things can happen like you modifying VRAM yourself. Mentioning that the origin is from the literal beam inside a CRT TV so it doesn't seem arbitrary.

If I saw a paragraph+diagram explaining that it would give a lot more context for further discussion of what the PPU and CPU are doing, and when VBlank is relative to everything else going on, and why they have these time limits (HBlank is short because the beam should quickly move on to the next row, etc).

2022-07-11 22:09 UTC, eievui5 commented on src/part2/getting-started.md
> +The next few lines wait until "VBlank". This basically means that the Game Boy's PPU has went to sleep for a short time, during which we can do things like turning off the screen.
I wanna know what ISSO's plans are for that stuff, but I'm open to explaining it here.

2022-07-11 23:15 UTC, eievui5 commented
I'm not sure about this layout for the logo name, link and source; any feedback?

![image](https://user-images.githubusercontent.com/14899090/178374138-166f8943-cfe1-492b-b169-c33d29b07f57.png)

2022-07-11 23:32 UTC, ISSOtm requested changes
Thanks a lot for doing this!

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +This defines a row of 8 pixels.
```suggestion
We will use `dw` instead of `db` (the difference between these two will be explained later); and for each row of pixels, instead of writing [the bitplanes](../part1/tiles#encoding) as raw numbers, we will use a backtick (\`) followed by 8 characters.
Each character defines a single pixel, intuitively from left to right; it must be one of 0, 1, 2, and 3, representing the corresponding color index in [the palette](../part1/palettes).
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +Tiles:
```suggestion
For example:

```rgbasm
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +(A note about OPT g could be added here?)
This would be a footnote attached to the "0, 1, 2, 3" snippet. It must also include [a link to the docs](https://rgbds.gbdev.io/docs/v0.5.2/rgbasm.5/#Changing_options_while_assembling).

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +We already have tiles made for this project, so you can copy [this premade file](https://github.com/ISSOtm/gb-asm-tutorial-part2/raw/main/tileset.asm), and paste it at the end of your code.
The lines must be included inline (possibly with a `max-height` applied to the block), especially since there is a handy "copy to clipboard" button.

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +Then copy the tilemap from [this file](https://github.com/ISSOtm/gb-asm-tutorial-part2/raw/main/tilemap.asm), and paste it after the `TilesEnd` label.
Same.

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +You can try building the rom at this point, using the following commands in your terminal:
```suggestion
You can build the ROM now, by running the following commands in your terminal:
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +If you paid attention to your tiles earlier, you may have noticed this comment:
```suggestion
You may have noticed this comment earlier, somewhere in the tile data:
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +The logo tiles were left intentionally blank so that you could customize this project.
```suggestion
The logo tiles were left intentionally blank so that you can choose your own.
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +If you feel up to it, you can try creating your own logo by hand, or you can copy one of the following logos into your code:
```suggestion
You can use one of the following pre-made logos, or try coming up with your own!
```

2022-07-11 23:32 UTC, ISSOtm commented on src/part2/getting-started.md
> +Build your game again and your logo of choice should appear in the bottom right!
```suggestion
Replace the blank tiles with the new graphics, build the game again, and you should see your logo of choice in the bottom-right!
```

2022-07-11 23:53 UTC, eievui5 commented on src/part2/getting-started.md
> +The next few lines wait until "VBlank". This basically means that the Game Boy's PPU has went to sleep for a short time, during which we can do things like turning off the screen.
Judging by Lesson 2, it looks like VBlank is a topic for even later.
> OAM accessibility will be glossed over, as explaining the concept of VBlank is a bit of a rabbit hole, and doing the update just after the "pacing wait" will mask that problem.

2022-07-11 23:55 UTC, eievui5 commented on src/part2/getting-started.md
> +The next few lines wait until "VBlank". This basically means that the Game Boy's PPU has went to sleep for a short time, during which we can do things like turning off the screen.
Also this:
https://github.com/ISSOtm/gb-asm-tutorial/pull/21/files#r918407321

2022-07-11 23:58 UTC, eievui5 commented on src/part2/getting-started.md
> +It copies `Tiles` to `$9000`, which is the part of VRAM where tiles are stored.
> which is a/the part of VRAM where tiles are stored.
This originally said "a" but @avivace suggested I change it, maybe he wants to give some input on this?

2022-07-12 00:01 UTC, eievui5 commented on src/part2/getting-started.md
> +![Layout of unbricked](https://github.com/ISSOtm/gb-asm-tutorial-part2/blob/main/tilemap.png?raw=true)
Yes, I agree. I can add `assets/part2` in this PR and we can move part 1 into `assets/part1` in another.

2022-07-12 08:37 UTC, ISSOtm commented on src/part2/getting-started.md
> +It copies `Tiles` to `$9000`, which is the part of VRAM where tiles are stored.
$9000 is not the beginning of that area, so I think calling it "the" is wrong.

2022-07-15 21:52 UTC, avivace requested changes

2022-07-15 21:52 UTC, avivace commented on src/part2/getting-started.md
> +We will make a [Breakout](https://en.wikipedia.org/wiki/Breakout_%28video_game%29) / [Arkanoid](https://en.wikipedia.org/wiki/Arkanoid) clone, which we'll "Unbricked"!
```suggestion
We will make a [Breakout](https://en.wikipedia.org/wiki/Breakout_%28video_game%29) / [Arkanoid](https://en.wikipedia.org/wiki/Arkanoid) clone, which we'll call "Unbricked"!
```

2022-07-15 21:52 UTC, avivace commented on src/part2/getting-started.md
> +To access other parts of the system, like the screen, buttons, or audio, you use special registers known as "I/O" registers.
Maybe a link to https://en.wikipedia.org/wiki/Memory-mapped_I/O could help here?

2022-07-15 21:52 UTC, avivace commented on src/part2/getting-started.md
> +It copies `Tiles` to `$9000`, which is the part of VRAM where tiles are stored.
My suggestion meant to try to clarify what $9000 was (a choice in a range?)

2022-07-15 21:52 UTC, avivace commented on src/part2/getting-started.md
> +We already have tiles made for this project, so you can copy [this premade file](https://github.com/ISSOtm/gb-asm-tutorial-part2/raw/main/tileset.asm), and paste it at the end of your code.
I don't think #17 should be blocking, as it involves a large amount of work to set everything up. Please just start with the example code "imported"..

2022-07-20 19:33 UTC, Rangi42 commented on src/part2/getting-started.md
> +It copies `Tiles` to `$9000`, which is the part of VRAM where tiles are stored.
`_VRAM + $1000`?

2022-08-05 09:55 UTC, avivace commented on src/part2/getting-started.md
> +(Screenshot pending :P)
TODO

2022-08-11 16:00 UTC, eievui5 commented
I've just added the code to this lesson, using the same method as part 1. It should be ready to release now.

2022-08-12 18:10 UTC, ISSOtm requested changes
Almost done! Also, line 109 still refers to gb-asm-tutorial-part2.

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +`$9000` is the first background tile, so it's assigned an ID of 0, and every tile after it is just one ID higher.
Isn't this redundant with Part I?

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +It copies `Tiles` to `$9000`, which is the part of VRAM where our tiles are going to be stored.
```suggestion
It copies starting at `Tiles` to `$9000` onwards, which is the part of VRAM where our [tiles](../part1/tiles.md) are going to be stored.
```

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +You can use [`OPT g`](https://rgbds.gbdev.io/docs/v0.5.2/rgbasm.5/#Changing_options_while_assembling) to modify these characters to your liking.
```suggestion
If the character selection isn't to your liking, you can use [RGBASM's `-g` option](https://rgbds.gbdev.io/docs/v0.5.2/rgbasm.1#g) or [`OPT g`](https://rgbds.gbdev.io/docs/v0.5.2/rgbasm.5/#Changing_options_while_assembling) to pick others.
For example, `rgbasm -g '.xXO' (...)` or `OPT g.xXO` would swap the four characters to `.`, `x`, `X`, and `O` respectively.
```

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +We will use `dw` instead of `db` (the difference between these two will be explained later); and for each row of pixels, instead of writing [the bitplanes](../part1/tiles.md#encoding) as raw numbers,
```suggestion
For each row of pixels, instead of writing [the bitplanes](../part1/tiles.md#encoding) directly, we will use a backtick (`` ` ``) followed by 8 characters.
```

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +
```suggestion

You may have noticed that we are using `dw` instead of `db`; the difference between these two will be explained later.
```

2022-08-12 18:10 UTC, ISSOtm commented on src/part2/getting-started.md
> +[Source](../../unbricked/getting-started/tail.asm)
```suggestion
- **RGBDS Logo**

  ![The RGBDS Logo](../assets/part2/rgbds.png)

  [Source](../../unbricked/getting-started/rgbds.asm)

- **Duck**

  ![A pixel-art duck](../assets/part2/duck.png)

  [Source](../../unbricked/getting-started/duck.asm)

- **Tail**

  ![A silhouette of a tail](../assets/part2/tail.png)

  [Source](../../unbricked/getting-started/tail.asm)
```

2022-08-12 18:44 UTC, eievui5 commented on src/part2/getting-started.md
> +`$9000` is the first background tile, so it's assigned an ID of 0, and every tile after it is just one ID higher.
Avivace [suggested I clarify it](https://github.com/ISSOtm/gb-asm-tutorial/pull/21#discussion_r922537838).

2022-08-12 18:46 UTC, ISSOtm commented on src/part2/getting-started.md
> +`$9000` is the first background tile, so it's assigned an ID of 0, and every tile after it is just one ID higher.
```suggestion
Recall that `$9000` is where the data of background tile $00 lies, and the data of subsequent tiles follows right after.
```

2022-08-13 00:53 UTC, avivace approved these changes

2022-08-13 07:47 UTC, ISSOtm approved these changes

2022-08-13 08:03 UTC, merged