text change
ISSOtm/gb-asm-tutorial pull request #29
Opened 2022-07-28 09:01 UTC by return2monki

I didn't build mdbook here but the link should work correctly. One thing I noticed is that the next hexadecimal section makes a little less sense now as I intentionally left out the underscores after mentioning them. They could just be added anyway, I don't think it matters too much.

2022-07-28 10:14 UTC, return2monki reviewed
changed to 1028 (didn't see this was asked for initially)

2022-07-29 20:47 UTC, ISSOtm requested changes
Underscores are intentionally not used so as to drive the point home better.

2022-07-29 20:47 UTC, ISSOtm commented on src/part1/bin_and_hex.md
> +So, by applying the same principle, we can say that in base 2, 42 is written as `10_1010`, and 1028 as `100_0000_0000`. Underscores are used here to improve readability[^underscores].
```suggestion
So, by applying the same principle, we can say that in base 2, 42 is written as `101010`, and 2048 as `10000000000`. 
```

2022-07-29 20:47 UTC, ISSOtm commented on src/part1/bin_and_hex.md
> +[^underscores]:
```suggestion
[^underscores]:
```

2022-07-29 21:03 UTC, return2monki commented on src/part1/bin_and_hex.md
> +So, by applying the same principle, we can say that in base 2, 42 is written as `10_1010`, and 1028 as `100_0000_0000`. Underscores are used here to improve readability[^underscores].
Understandable, 1 more 0 has to be added if you want it to be 2048 right?

2022-07-29 21:07 UTC, ISSOtm commented on src/part1/bin_and_hex.md
> +So, by applying the same principle, we can say that in base 2, 42 is written as `10_1010`, and 1028 as `100_0000_0000`. Underscores are used here to improve readability[^underscores].
Yes, but I want there to be a mistake—to make the reader *experience* why it's inconvenient.

2022-07-29 21:13 UTC, return2monki commented
Ok that's it, I didn't realize the first binary number was intentionally wrong.

2022-07-29 21:15 UTC, ISSOtm commented
Ah, only the latter (under "hexadecimal") is supposed to. The block just above also specifies 1024 instead of 2048, so it's likely a copy-paste error; *that* one should be made right.

2022-07-29 21:17 UTC, return2monki commented
> Ah, only the latter (under "hexadecimal") is supposed to. The block just above also specifies 1024 instead of 2048, so it's likely a copy-paste error; _this_ one should be made right.

I made it 1024 myself, before all this it was 2048 with 10 digits. Do you want 1024 or 2048 with correct binary?

2022-07-29 21:22 UTC, ISSOtm commented
It should be 1024 for consistency with the preformatted block above.

2022-07-29 21:25 UTC, ISSOtm approved these changes

2022-07-29 21:26 UTC, merged