Add Chapter 2 Lesson 2
ISSOtm/gb-asm-tutorial pull request #31
Opened 2022-08-25 16:21 UTC by eievui5

Closes #13

2022-08-25 17:38 UTC, ISSOtm requested changes
Don't forget to add the lesson to `SUMMARY.md`!

2022-08-25 17:38 UTC, ISSOtm commented on src/part2/objects.md
> +
```suggestion

Each object allows drawing one or two tiles (so 8×8 or 8×16 pixels, respectively) at any on-screen position—unlike the background, where all the tiles are drawn in a grid.
Therefore, an object consists of its on-screen position, a tile ID (like [with the tilemap](../part1/tilemap.md)), and some extra properties called "attributes".
These extra properties allow "flipping" the tile for free, for example; we'll see more about them later.

```

2022-08-25 17:38 UTC, ISSOtm commented on src/part2/objects.md
> +
```suggestion
There is a catch, though: an object's Y and X coordinate bytes in OAM do *not* store its on-screen position!
Instead, the *on-screen* X position is the *stored* X position **minus 8**, and the *on-screen* Y position is the *stored* Y position **minus 16**.
If we do not want to use an object, we can simply put it off-screen; setting its Y position to 0 will do just fine.

::: tip

These offsets are not arbitrary!
Consider an object's maximum size: 8 by 16 pixels.
These offsets allow objects to be clipped by the left and top edges of the screen.
The NES, for example, lacks such offsets—so you will notice that objects always disappear after hitting the left or top edge of the screen.

:::

```

2022-08-25 17:38 UTC, ISSOtm commented on src/part2/objects.md
> +In addition, the screen must be off to access OAM, just like VRAM.
```suggestion
In addition, the screen must be off to safely access OAM, just like VRAM.
```

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	xor a, a ; ld a, 0
```suggestion
	ld a, 0
```
It's too early for that!

2022-08-25 17:38 UTC, ISSOtm commented on src/part2/objects.md
> +This means that the Y position of our object is 144, the X position is 24, and the tile ID and attributes are both set to 0.
```suggestion
So, the object lies at Y = 144 - 16 = 128, and at X = 24 - 8 = 16.
The tile ID and attributes are both set to 0.
```

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	ld a, 144
```suggestion
	ld a, 144 ; 128 + 16
```
or
```suggestion
	ld a, 128 + 16
```

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	ld a, 24
```suggestion
	ld a, 24 ; 16 + 8
```
or
```suggestion
	ld a, 16 + 8
```

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	xor a, a ; ld a, 0
```suggestion
	ld a, 0
```
I know, it's hard, but Part III will be cathartic for the both of us. Look forward to that! ;P

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	xor a, a ; ld a, 0
```suggestion
	ld a, 0
```
\*pats the eevee\*

2022-08-25 17:38 UTC, ISSOtm commented on src/part2/objects.md
> +
```suggestion

::: tip:🤔

We mentioned above that the screen must be turned off to access OAM safely.
There is another way, but it would be too complicated to explain right now, so we will talk about it later.

:::

```

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	jr nz, Main
This is bugged, as it jumps back to `Main` during VBlank.

2022-08-25 17:38 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	jr nz, CopyTiles
```suggestion
	jr nz, CopyTiles
```
Ah, by the way, we haven't explained `jr` yet. These should be `jp` instead (including in the previous lesson, if I missed them there).

2022-09-06 23:29 UTC, eievui5 commented on unbricked/objects/main.asm
> +	jr nz, CopyTiles
You told me in the discord that it was okay to use `jr`; they were used (and explained i think?) in the previous lesson.

2022-09-06 23:34 UTC, eievui5 commented on unbricked/objects/main.asm
> +	jr nz, Main
Hmm, how should I solve this in a way that's not overly confusing?

2022-09-09 12:04 UTC, avivace commented on unbricked/objects/main.asm
> +	jr nz, CopyTiles
`jr` instructions are used in the previous lesson too. Maybe we can explain it there?

2022-09-15 07:00 UTC, avivace requested changes
Thanks @eievui5 ! Looks mostly okay to me. 

Two points:

-  I don't see the reason in adding complexities we can't / want to explain now, those boxes just lead to more cognitive load without actually teaching anything
- There are a lot of repetitions and "as we've seen before" and this is now appearing very often. The tutorial is supposed to be read in sequence, so I don't see the reason in having 3-5 points in every lesson telling that we are continuining from before

2022-09-15 11:01 UTC, eievui5 commented on src/part2/objects.md
> +The NES, for example, lacks such offsets—so you will notice that objects always disappear after hitting the left or top edge of the screen.
I didn’t write that but i think it’s supposed to be a [https://en.m.wikipedia.org/wiki/Dash](dash)

2022-09-15 20:35 UTC, eievui5 commented on src/part2/objects.md
> +These extra properties allow "flipping" the tile for free, for example; we'll see more about them later.
Maybe this would be better:
```suggestion
These extra properties allow flipping the tile, for example; we'll learn more about them later.
```

2022-09-18 10:51 UTC, ISSOtm commented on src/part2/objects.md
> +These extra properties allow "flipping" the tile for free, for example; we'll see more about them later.
It's "free" because it does not require us to write any code that does it. (Which also implies that it costs no bytes nor cycles, but that doesn't need to be said.)

2022-09-18 10:56 UTC, ISSOtm commented on src/part2/objects.md
> +The NES, for example, lacks such offsets—so you will notice that objects always disappear after hitting the left or top edge of the screen.
Correct, specifically, [an equivalent of parens](https://en.wikipedia.org/wiki/Dash#Parenthesis-like_use). I think it adds a bit of variety, too many parens feel heavy to read.

That said, for this specific usage, a comma might be better.

2022-09-18 11:03 UTC, ISSOtm commented on src/part2/objects.md
> +We mentioned above that the screen must be turned off to access OAM safely.
It's because we are accessing OAM without turning the LCD off. I agree we should word it differently.

2022-09-18 11:09 UTC, ISSOtm commented on src/part2/objects.md
> +These extra properties allow "flipping" the tile for free, for example; we'll see more about them later.
Here's my suggestion:
```suggestion
These extra properties allow, for example, to display the tile flipped.
We'll see more about them later.
```

2022-09-18 11:10 UTC, ISSOtm commented on src/part2/objects.md
> +There is another way, but it would be too complicated to explain right now, so we will talk about it later.
```suggestion
::: tip:🤨

Here, we are accessing OAM safely without turning the LCD off.
Explaining why requires a more thorough explanation of the Game Boy's rendering, so let's ignore it for now.
```
Is this clearer?

2022-09-18 11:39 UTC, ISSOtm commented on unbricked/objects/main.asm
> +	jr nz, Main
I changed `Main` to wait for "not VBlank" before waiting for VBlank. Does that seem good to you?

2022-09-18 13:02 UTC, eievui5 commented on unbricked/objects/main.asm
> +	jr nz, Main
It works, though that `WaitVBlank2` label hurts :P

2022-09-19 07:49 UTC, avivace commented on src/part2/objects.md
> +These extra properties allow "flipping" the tile for free, for example; we'll see more about them later.
I like @ISSOtm proposed alternative, but both are good!

2022-09-19 07:51 UTC, avivace commented on src/part2/objects.md
> +The NES, for example, lacks such offsets—so you will notice that objects always disappear after hitting the left or top edge of the screen.
I don't think they should be used as interchangeable. Not a lot of variety is good so the focus shifts on content. I'm okay with `-` being used as commas if we want to express a different degree of demarcation (See "Subtle differences in punctuation" in the wikipedia article linked).

2022-10-05 17:18 UTC, eievui5 commented on src/part2/objects.md
> +This can hide bugs in your game and seriously hurts performance.
Nevermind, it looks like this was already removed

2022-10-05 17:31 UTC, ISSOtm commented
Ah, yeah, this is a thing... sorry it fell off my TODO list. Will perform a full review shortly, apologies.

2022-10-06 07:28 UTC, avivace approved these changes
Nice job @eievui5 ! I really like this, it reads very smooth and presents a couple of concepts very clearly.

I just left some suggestions but nothing major. I think we are only missing the BGB screenshot to merge this ;)

2022-10-06 07:28 UTC, avivace commented on src/part2/objects.md
> +First off, when the Game Boy is powered on, OAM is filled with a bunch of semi-random garbage values, which may cover the screen with some random garbage.
```suggestion
First off, when the Game Boy is powered on, OAM is filled with a bunch of semi-random values, which may cover the screen with some random garbage.
```

To avoid repetition

2022-10-06 07:28 UTC, avivace commented on src/part2/objects.md
> +> Graphic showing the view of BGB :)
It this a placeholder? We still need to add the image

2022-10-06 07:28 UTC, avivace commented on src/part2/objects.md
> +Thankfully, the Game Boy has a feature that's perfect for these!
```suggestion
The Game Boy has a feature that's perfect for these!
```
I'm not particularly fond of the usage of "thankfully" here, I don't think it really adds any meaning.

2022-10-06 16:00 UTC, ISSOtm commented on src/part2/objects.md
> +Every 10th frame we'll move the paddle by one pixel, slowing it down to 1/6th the previous speed.
```suggestion
Every 10th frame, we'll move the paddle by one pixel, slowing it down to 6 pixels per second.
```
You mixed the numbers up here :P

2022-10-06 16:00 UTC, ISSOtm commented on src/part2/objects.md
> +Don't forget that variables have a *random value* when the Game Boy starts, so we need to initialize them before using them.
```suggestion
Don't forget that RAM is filled with garbage values when the Game Boy starts, so we need to initialize our variables before first using them.
```

2022-10-06 16:01 UTC, ISSOtm commented on src/part2/objects.md
> +```
~~~suggestion
```

Alright!
Up next is us taking control of that little paddle.
~~~

2022-10-06 16:02 UTC, ISSOtm commented on src/part2/objects.md
> +
```suggestion

## Movement

```

2022-10-08 10:30 UTC, avivace commented on src/part2/objects.md
> +```
Agree here

2022-10-12 16:59 UTC, avivace commented on src/part2/objects.md
> +> Graphic showing the view of BGB :)
Thanks @ISSOtm , looks good to me

2022-10-12 16:59 UTC, avivace commented on src/part2/objects.md
> +Once OAM is clear we can draw an object.
I'm not super fond of "writing its properties".. maybe a different wording here?

2022-10-17 19:50 UTC, ISSOtm approved these changes

2022-10-17 19:50 UTC, merged